### ISSUE TITLE
Fatal error whenever I use a page selector with Open Graph Tags active

### ISSUE THREAD

**Issue by dangrth** [hissy/c5-open-graph-tags-lite#19]
Steps to reproduce :
* activate Open Graph Lite
* edit any text on the site
* insert a link and pick the page selector

Then the page selector never displays and AJAX keeps loading.
In the php error log, I get :
PHP Fatal error:  Call to a member function getPageController() on null in /web/packages/open_graph_tags_lite/src/Html/OpenGraphTags.php on line 20

**Comment by dangrth** [comment]
The problem is solved by adding a guard, but I haven't tested for side effets:            
if(!is_object($page)) {
    return;
}

**Comment by hissy** [comment]
Maybe related #20

**Comment by hissy** [comment]
Fixed with #20
